{
    'name': 'Inventory Management',
    'version': '1.0',
    'summary': 'Manage inventory with serial and batch tracking',
    'description': 'Track products in inventory using serial numbers and batch tracking features.',
    'category': 'Inventory',
    'author': 'Adham',
    'depends': ['base', 'stock'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/sample_data.xml',
        # 'data/inventory_reports.xml',
        # 'reports/product_batch_report.xml',
        # 'reports/product_serial_report.xml', 
        'views/product_views.xml',
        'views/batch_views.xml',
        'views/serial_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}
